### PR TITLE
45 fix hints and errors

### LINKED ISSUE #45: Fix hints and errors
When running `npm run check` svelte finds over 50 hints and 2 errors. Check what they are and fix them.

### PR DESCRIPTION
**Pull request by Schereo**
# Description of change

Fixed all typescript errors and some hints

## Links to any relevant issues

closes #45 

## Type of change

-   Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Manual testing

## Change checklist

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: src/lib/app/base.ts [hunk 1]
```diff
@@ -3,8 +3,7 @@ import { ApiVersion, ChannelClient, IdentityClient } from '@iota/is-client'
 import { derived, get } from 'svelte/store'
 import { logout } from './identity'
 import { showNotification } from './notification'
-import { NotificationType, UserRoles } from './types'
-import type { JwtUser } from './types'
+import { NotificationType, UserRoles, type JwtUser } from './types'
```
Comment (dominic22) [inline src/lib/app/base.ts:6]: `type JwtUser` returns an error for me I don't know why not for you? Do you have an idea?

Comment (dominic22) [reply src/lib/app/base.ts:6]:
```
import { NotificationType, UserRoles } from './types'
import type { JwtUser } from './types'
```
Works for me

**Review by dominic22 — APPROVED** [review]
